defaults:
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled
  - _self_

dataset:
  _target_: winlp.task.token_classification.boundary_detection.BoundaryDetectionDataModule
  batch_size: 4
  dataset_name:
  - /home/bryant/Chest-CT-Segment-Event/chest_ct_event/program_data/chest_ct_event_2024-01-23-07-56
  indices_column_name: Indices
  label_column_name: Tags
  label_list:
  - O
  - COMP
  - FIND
  - IMP
  - EVENT
  - Others
  max_length: 512
  num_workers: null
  pretrained_model_name_or_path: microsoft/deberta-v3-base
seed: 1314
task:
  _target_: winlp.task.token_classification.boundary_detection.BoundaryDetectionModule
  learning_rate: 0.0001
  mode: max
  monitor: val_f1
  pretrained_model_name_or_path: microsoft/deberta-v3-base
  warmup_ratio: 0.1
  weight_decay: 0.01
test: true
trainer:
  _target_: lightning.pytorch.Trainer
  accelerator: auto
  deterministic: true
  devices: auto
  logger:
    _target_: lightning.pytorch.loggers.MLFlowLogger
    experiment_name: Chest-CT-Event-Segmentation
    run_name: run_1
    tracking_uri: http://192.168.1.76:9487
  max_epochs: 20

hydra:
  output_subdir: null
  run:
    dir: .